In [0]:
#https://www.youtube.com/watch?v=9siFuMMHNIA
import numpy as np
import pandas as pd

In [14]:
matrix = np.array([[5, 5, 0, 0], [5, None, None, 0], [None, 4, 0, None], [0, 0, 5, 4], [0, 0, 5, None]])

n_u = 4 #4 users
n_m = 5 #5 movies

#movie_features = np.array([[0.9, 0], [1.0, 0.01], [0.99, 0], [0.1, 1.0], [0, 0.9]])
movie_features = np.array([[1, 0.9, 0], [1, 1.0, 0.01], [1, 0.99, 0], [1, 0.1, 1.0], [1, 0, 0.9]], dtype=float)

n = 2 #number of features

theta = np.array([[2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2]], dtype=float)

print(theta[0].transpose().dot(movie_features[2]))  #prediction 1 (real value: 5)

3.98


In [0]:
#variables
def r(matrix, i, j):
  if(matrix[i][j] != None):
    return 1
  else:
    return 0

In [0]:
def loss(matrix, n_m, n_u):
  total = 0
  for i in range(n_m):
    for j in range(n_u):
      if(r(matrix, i, j) == 1):
        total += (theta[j].transpose().dot(movie_features[i]) - matrix[i][j])**2
  return (total)

In [0]:
def gradient_descent(matrix, theta, movie_features, n_m, n_u, k):
  total = 0
  for i in range(n_m):
    for j in range(n_u):
      if(r(matrix, i, j) == 1):
        total += (theta[j].transpose().dot(movie_features[i]) - matrix[i][j])*movie_features[i][k]
  return total
learn_rate = 0.0001


print(theta[0])

tempOut = 0.00
print("loss before: ", loss(matrix, n_m, n_u))

for t in range(10):
  theta[0][0] = float(theta[0][0]) - float(learn_rate * gradient_descent(matrix, theta, movie_features, n_m, n_u, 0))
  theta[0][1] = float(theta[0][1]) -  float(learn_rate * gradient_descent(matrix, theta, movie_features, n_m, n_u, 1))
  theta[0][2] = float(theta[0][2]) - float(learn_rate * gradient_descent(matrix, theta, movie_features, n_m, n_u, 2))

  tempOut = tempOut - float(learn_rate * gradient_descent(matrix, theta, movie_features, n_m, n_u, 0))

print(theta[0])
print("loss after: ", loss(matrix, n_m, n_u))

[2.5 2.5 2.5]
loss before:  198.14
[2.45885979 2.47982234 2.47968554]
loss after:  196.95045408320067


In [0]:
#Combine
matrix = np.array([[5, 5, 0, 0], [5, None, None, 0], [None, 4, 0, None], [0, 0, 5, 4], [0, 0, 5, None]])

n_u = 4 #4 users
n_m = 5 #5 movies

#movie_features = np.array([[0.9, 0], [1.0, 0.01], [0.99, 0], [0.1, 1.0], [0, 0.9]])
movie_features = np.array([[1, 0.9, 0], [1, 1.0, 0.01], [1, 0.99, 0], [1, 0.1, 1.0], [1, 0, 0.9]], dtype=float)

n = 2 #number of features

theta = np.array([[2.5, 2.5, 2.5], [2, 2, 2], [2, 2, 2], [2, 2, 2]], dtype=float)

print(theta[0].transpose().dot(movie_features[2]))  #prediction 1 (real value: 5)

def totalLoss(matrix, n_m, n_u):
  total = 0
  for i in range(n_m):
    for j in range(n_u):
      if(r(matrix, i, j) == 1):
        total += (theta[j].transpose().dot(movie_features[i]) - matrix[i][j])**2
  return (total)

def loss(matrix, n_m, j):
  total = 0
  for i in range(n_m):
    if(r(matrix, i, j) == 1):
      total += (theta[j].transpose().dot(movie_features[i]) - matrix[i][j])**2
  return (total)


def gradient_descent(j, matrix, theta, movie_features, n_m, n_u, k):
  total = 0
  for i in range(n_m):
    if(r(matrix, i, j) == 1):
      total += (theta[j].transpose().dot(movie_features[i]) - matrix[i][j])*movie_features[i][k]
  return total
learn_rate = 0.0001


print(theta[0])

tempOut = 0.00
print("loss before: ", totalLoss(matrix, n_m, n_u))
for j in range(n_u):
  breakOut = False
  for t in range(100000):
    theta[j][0] = float(theta[j][0]) - float(learn_rate * gradient_descent(0, matrix, theta, movie_features, n_m, n_u, 0))
    theta[j][1] = float(theta[j][1]) -  float(learn_rate * gradient_descent(0, matrix, theta, movie_features, n_m, n_u, 1))
    theta[j][2] = float(theta[j][2]) - float(learn_rate * gradient_descent(0, matrix, theta, movie_features, n_m, n_u, 2))

    if(t == 0):
      minVal = loss(matrix, n_m, j)    
    else:
      currentVal = loss(matrix, n_m, j)
      if(currentVal > minVal):
        print("j:", j, "t:", t)
        print("\tmin:", minVal, "current:", currentVal)
        break
      else:
        minVal = currentVal

  print(theta[j])

print("loss after: ", totalLoss(matrix, n_m, n_u))  #89.69

4.975
[2.5 2.5 2.5]
loss before:  146.70932499999998
[ 1.02328529  4.18347893 -1.29695888]
[2.1709244  1.82163245 1.82967682]
j: 2 t: 1
	min: 32.3604001919833 current: 32.36040038396675
[2.00000342 1.99999643 1.99999659]
[2.1709244  1.82163245 1.82967682]
loss after:  96.60949978479799


In [0]:
#Combine
matrix = np.array([[5, 5, 0, 0], [5, None, None, 0], [None, 4, 0, None], [0, 0, 5, 4], [0, 0, 5, None]])

n_u = 4 #4 users
n_m = 5 #5 movies

#movie_features = np.array([[0.9, 0], [1.0, 0.01], [0.99, 0], [0.1, 1.0], [0, 0.9]])
movie_features = np.array([[1, 0.9, 0], [1, 1.0, 0.01], [1, 0.99, 0], [1, 0.1, 1.0], [1, 0, 0.9]], dtype=float)

n = 2 #number of features

theta = np.array([[2.5, 2.5, 2.5], [2.5, 2.5, 2.5], [2.5, 2.5, 2.5], [2.5, 2.5, 2.5]], dtype=float)

print(theta[0].transpose().dot(movie_features[2]))  #prediction 1 (real value: 5)

def totalLoss(matrix, theta, movie_features, n_m, n_u):
  total = 0
  for i in range(n_m):
    for j in range(n_u):
      if(r(matrix, i, j) == 1):
        total += (theta[j].transpose().dot(movie_features[i]) - matrix[i][j])**2
  return (total)

def loss(matrix, theta, movie_features, n_m, j):
  total = 0
  for i in range(n_m):
    if(r(matrix, i, j) == 1):
      total += (theta[j].transpose().dot(movie_features[i]) - matrix[i][j])**2
  return (total)


def gradient_descent(j, matrix, theta, movie_features, n_m, n_u, k):
  total = 0
  for i in range(n_m):
    if(r(matrix, i, j) == 1):
      total += (theta[j].transpose().dot(movie_features[i]) - matrix[i][j])*movie_features[i][k]
  return total
learn_rate = 0.0001


print(theta[0])

tempOut = 0.00
print("loss before: ", totalLoss(matrix, theta, movie_features, n_m, n_u))
for j in range(n_u):
  breakOut = False
  t = 0
  while(breakOut == False and t < 500000):
    theta[j][0] = float(theta[j][0]) - float(learn_rate * gradient_descent(j, matrix, theta, movie_features, n_m, n_u, 0))
    theta[j][1] = float(theta[j][1]) - float(learn_rate * gradient_descent(j, matrix, theta, movie_features, n_m, n_u, 1))
    theta[j][2] = float(theta[j][2]) - float(learn_rate * gradient_descent(j, matrix, theta, movie_features, n_m, n_u, 2))

    if(t == 0):
      minVal = loss(matrix, theta, movie_features, n_m, j)
    else:
      currentVal = loss(matrix, theta, movie_features, n_m, j)
      if(currentVal > minVal and t>1000):
        print("j:", j, "t:", t)
        print("\tmin:", minVal, "current:", currentVal)
        breakOut = True
      else:
        minVal = currentVal
    t += 1
  print(j, theta[j], minVal)

print("loss after: ", totalLoss(matrix, theta, movie_features, n_m, n_u))  #89.69


print("\n\n\n")
for i in range(5):
  print(matrix[i])
print("\n\n\n")

for i in range(n_m):
  for j in range(n_u):
    if(matrix[i][j] == None):
      matrix[i][j] = round(theta[j].transpose().dot(movie_features[i]), 2)
for i in range(5):
  print(matrix[i])

4.975
[2.5 2.5 2.5]
loss before:  198.14
0 [ 1.59871651  3.58286865 -1.87046307] 0.07241691654704834
1 [ 1.95776048  2.66923296 -2.19125888] 0.7711954366224806
2 [ 1.26735312 -1.34122711  3.99615959] 0.0425513939365714
3 [ 0.40840046 -0.4488888   3.63637967] 3.638843702945191e-05
loss after:  0.8862001355431298




[5 5 0 0]
[5 None None 0]
[None 4 0 None]
[0 0 5 4]
[0 0 5 None]




[5 5 0 0]
[5 4.61 -0.03 0]
[5.15 4 0 -0.04]
[0 0 5 4]
[0 0 5 3.68]


In [0]:
print(movie_features)

[[1.   0.9  0.  ]
 [1.   1.   0.01]
 [1.   0.99 0.  ]
 [1.   0.1  1.  ]
 [1.   0.   0.9 ]]
